### PR TITLE
add mine to the code

### PR DESCRIPTION
**Pull request by Xpl0itU**
add mine to the code

### CODE REVIEW

**Comment by pavlukivan** [comment]
no cuz linux version supports mac

**Comment by Xpl0itU** [comment]
No,it doesn't

**Comment by pavlukivan** [comment]
it does, ur just doing it wrong

**Comment by Xpl0itU** [comment]
No,it doesnt,try it yourself in a os x 10.9 vm

**Comment by pavlukivan** [comment]
*ur just doing it wrong*

**Pull request closed without merging**
